# Generated by Django 2.0.1 on 2018-04-19 22:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=datetime.date.today, verbose_name='date consumed')),
                ('servings', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('serving_unit', models.CharField(editable=False, max_length=200)),
                ('calories', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serving_size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('serving_unit', models.CharField(choices=[('c', 'cups'), ('g', 'grams'), ('oz', 'ounces'), ('lb', 'pounds'), ('tbsp', 'tablespoons'), ('tsp', 'teaspoons')], default='g', max_length=32)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.Food'),
        ),
    ]
